# Generated by Django 4.1.7 on 2023-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalStore", "0006_auto_20190403_1046"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="description",
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
