# Generated by Django 4.1.7 on 2023-04-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalStore", "0008_alter_medicine_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="description",
            field=models.CharField(default="Not Available", max_length=150, null=True),
        ),
    ]
